runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /api.*
  script: api_router.routes

- url: /woker.*
  script: worker_router.routes
  login: admin


libraries:
- name: webapp2
  version: "2.5.2"
